In [13]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [14]:
df = pd.read_csv("../dataset/Obfuscated-MalMem2022.csv")

df.head()

,Category,pslist.nproc,pslist.nppid,pslist.avg_threads,pslist.nprocs64bit,pslist.avg_handlers,dlllist.ndlls,dlllist.avg_dlls_per_proc,handles.nhandles,handles.avg_handles_per_proc,...,svcscan.kernel_drivers,svcscan.fs_drivers,svcscan.process_services,svcscan.shared_process_services,svcscan.interactive_process_services,svcscan.nactive,callbacks.ncallbacks,callbacks.nanonymous,callbacks.ngeneric,Class
0,Benign,45,17,10.555555,0,202.84445,1694,38.500000,9129,212.30232,...,221,26,24,116,0,121,87,0,8,Benign
1,Benign,47,19,11.531915,0,242.23404,2074,44.127660,11385,242.23404,...,222,26,24,118,0,122,87,0,8,Benign
2,Benign,40,14,14.725000,0,288.22500,1932,48.300000,11529,288.22500,...,222,26,27,118,0,120,88,0,8,Benign
3,Benign,32,13,13.500000,0,264.28125,1445,45.156250,8457,264.28125,...,222,26,27,118,0,120,88,0,8,Benign
4,Benign,42,16,11.452381,0,281.33334,2067,49.214287,11816,281.33334,...,222,26,24,118,0,124,87,0,8,Benign

In [15]:
X = df.drop(["Category","Class"], axis=1)

y = df["Class"]

le = LabelEncoder()

y = le.fit_transform(y)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [17]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Support Vector Machine": SVC()
}

In [18]:
results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)

    results.append([name, acc])

results

c:\Users\YASHINI STEVIYA A\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[['Logistic Regression', 0.9981054081984154],
 ['Decision Tree', 0.9993971753358595],
 ['Random Forest', 0.9999138821908371],
 ['Support Vector Machine', 0.9866517395797451]]

In [19]:
result_df = pd.DataFrame(results, columns=["Model","Accuracy"])

result_df

                    Model  Accuracy
0     Logistic Regression  0.998105
1           Decision Tree  0.999397
2           Random Forest  0.999914
3  Support Vector Machine  0.986652

In [20]:
best_model = result_df.sort_values(by="Accuracy", ascending=False)

best_model

                    Model  Accuracy
2           Random Forest  0.999914
1           Decision Tree  0.999397
0     Logistic Regression  0.998105
3  Support Vector Machine  0.986652

In [21]:
import joblib

best_model = RandomForestClassifier(random_state=42)
best_model.fit(X_train, y_train)

joblib.dump(best_model, "../models/malware_detector.pkl")

print("✅ Best model saved successfully!")

✅ Best model saved successfully!

In [24]:
sample = X_test.head(20)

sample.to_csv("../app/sample_test.csv", index=False)